all:
  task_trainer: "dem"
  hp:
    max_num_epochs: 5
    batch_size: 10
    memory:
      batch_size: 10
      downsample_size: 64
      loss_coef: 1.
      num_samples_per_class: "all"
    upsampler:
      mode: "nearest"
    lowres_training:
      loss_coef: 0.
      logits_matching_loss_coef: 0.
    # optim: {"type": "adam", "kwargs": {"lr": 0.001}}
    # optim: {"type": "sgd", "kwargs": {"lr": 0.003}}

cub:
  hp:
    pretrained: true
    img_target_shape: [256, 256]

awa:
  hp:
    pretrained: false
    img_target_shape: [256, 256]

tiny_imagenet:
  hp:
    img_target_shape: [64, 64]
