all:
  task_trainer: "ewc_online"
  hp:
    fisher:
      gamma: 0.99
      loss_coef: 10

  # validation_sequence:
  #   num_tasks: 3
  #   hpo_grid:
  #     fisher|loss_coef: [1, 10]
  #     fisher|gamma: [0.95, 0.99]
